#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace AnimBP_ORD_Dropship { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_Drill_Medium { struct FAnimBlueprintGeneratedConstantData; }

namespace BPAnim_CheckpointStation { struct FAnimBlueprintGeneratedConstantData; }

namespace AnimBP_Drill_Small { struct FAnimBlueprintGeneratedConstantData; }

namespace BPAnim_Player_StandIn { struct FAnimBlueprintGeneratedConstantData; }

