#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_ORD_Dropship

#include "Basic.hpp"

#include "GbxGame_classes.hpp"
#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AnimBP_ORD_Dropship.AnimBP_ORD_Dropship_C
// 0x0EB0 (0x14E0 - 0x0630)
class UAnimBP_ORD_Dropship_C final : public UGbxGameAnimInstance
{
public:
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0630(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0638(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0640(0x0028)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0668(0x0E78)()

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AnimBP_ORD_Dropship_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AnimBP_ORD_Dropship_C")
	}
	static class UAnimBP_ORD_Dropship_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimBP_ORD_Dropship_C>();
	}
};
DUMPER7_ASSERTS_UAnimBP_ORD_Dropship_C;

}

