#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Enum_Robo_Cards

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Enum_Robo_Cards.Enum_Robo_Cards
// NumValues: 0x000F
enum class Enum_Robo_Cards : uint8
{
	NewEnumerator13                          = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator3                           = 4,
	NewEnumerator4                           = 5,
	NewEnumerator5                           = 6,
	NewEnumerator6                           = 7,
	NewEnumerator7                           = 8,
	NewEnumerator8                           = 9,
	NewEnumerator9                           = 10,
	NewEnumerator10                          = 11,
	NewEnumerator11                          = 12,
	NewEnumerator12                          = 13,
	Enum_Robo_MAX                            = 14,
};

}

