#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PhotoMode

#include "Basic.hpp"

#include "PhotoMode_classes.hpp"
#include "PhotoMode_parameters.hpp"


namespace SDK
{

// Function PhotoMode.KPhotoModePawn.ActivatePhotoModePawn
// (Final, Native, Public)
// Parameters:
// class APlayerController*                InPlayerController                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::ActivatePhotoModePawn(class APlayerController* InPlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "ActivatePhotoModePawn");

	Params::KPhotoModePawn_ActivatePhotoModePawn Parms{};

	Parms.InPlayerController = InPlayerController;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.DeactivatePhotoModePawn
// (Final, Native, Public)

void AKPhotoModePawn::DeactivatePhotoModePawn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "DeactivatePhotoModePawn");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.EnableFocusOverride
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bIsEnable                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::EnableFocusOverride(bool bIsEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "EnableFocusOverride");

	Params::KPhotoModePawn_EnableFocusOverride Parms{};

	Parms.bIsEnable = bIsEnable;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.FindStartLocation
// (Final, Native, Private, HasDefaults)
// Parameters:
// const struct FVector&                   InLocation                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector AKPhotoModePawn::FindStartLocation(const struct FVector& InLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "FindStartLocation");

	Params::KPhotoModePawn_FindStartLocation Parms{};

	Parms.InLocation = std::move(InLocation);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModePawn.GetAllMeshComponents
// (Final, Native, Private)
// Parameters:
// const class AActor*                     InActor                                                (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class UMeshComponent*>           ReturnValue                                            (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, ContainsInstancedReference, NativeAccessSpecifierPublic)

TArray<class UMeshComponent*> AKPhotoModePawn::GetAllMeshComponents(const class AActor* InActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "GetAllMeshComponents");

	Params::KPhotoModePawn_GetAllMeshComponents Parms{};

	Parms.InActor = InActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModePawn.GetAllNiagaraComponents
// (Final, Native, Private)
// Parameters:
// const class AActor*                     InActor                                                (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class UNiagaraComponent*>        ReturnValue                                            (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, ContainsInstancedReference, NativeAccessSpecifierPublic)

TArray<class UNiagaraComponent*> AKPhotoModePawn::GetAllNiagaraComponents(const class AActor* InActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "GetAllNiagaraComponents");

	Params::KPhotoModePawn_GetAllNiagaraComponents Parms{};

	Parms.InActor = InActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModePawn.GetDistanceToPlayerCharacter
// (Final, Native, Private)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float AKPhotoModePawn::GetDistanceToPlayerCharacter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "GetDistanceToPlayerCharacter");

	Params::KPhotoModePawn_GetDistanceToPlayerCharacter Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModePawn.IsToggleableInteractiveObject
// (Final, Native, Private)
// Parameters:
// const class AActor*                     InteractiveObject                                      (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool AKPhotoModePawn::IsToggleableInteractiveObject(const class AActor* InteractiveObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "IsToggleableInteractiveObject");

	Params::KPhotoModePawn_IsToggleableInteractiveObject Parms{};

	Parms.InteractiveObject = InteractiveObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModePawn.KeepWithinRadius
// (Final, Native, Private)

void AKPhotoModePawn::KeepWithinRadius()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "KeepWithinRadius");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.OnEndTimelineFinished
// (Final, Native, Private)

void AKPhotoModePawn::OnEndTimelineFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "OnEndTimelineFinished");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.OnEndTimelineUpdate
// (Final, Native, Private)
// Parameters:
// float                                   ALPHA                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::OnEndTimelineUpdate(float ALPHA)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "OnEndTimelineUpdate");

	Params::KPhotoModePawn_OnEndTimelineUpdate Parms{};

	Parms.ALPHA = ALPHA;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.OnStartTimelineFinished
// (Final, Native, Private)

void AKPhotoModePawn::OnStartTimelineFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "OnStartTimelineFinished");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.OnStartTimelineUpdate
// (Final, Native, Private)
// Parameters:
// float                                   ALPHA                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::OnStartTimelineUpdate(float ALPHA)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "OnStartTimelineUpdate");

	Params::KPhotoModePawn_OnStartTimelineUpdate Parms{};

	Parms.ALPHA = ALPHA;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetActorVisibility
// (Final, Native, Private)
// Parameters:
// class AActor*                           InActor                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bIsVisible                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetActorVisibility(class AActor* InActor, bool bIsVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetActorVisibility");

	Params::KPhotoModePawn_SetActorVisibility Parms{};

	Parms.InActor = InActor;
	Parms.bIsVisible = bIsVisible;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetBloom
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InBloomIntensity                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetBloom(float InBloomIntensity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetBloom");

	Params::KPhotoModePawn_SetBloom Parms{};

	Parms.InBloomIntensity = InBloomIntensity;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetChromaticAberration
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InChromaticAberrationIntensity                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetChromaticAberration(float InChromaticAberrationIntensity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetChromaticAberration");

	Params::KPhotoModePawn_SetChromaticAberration Parms{};

	Parms.InChromaticAberrationIntensity = InChromaticAberrationIntensity;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetDamageNumbersVisibility
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bIsVisible                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetDamageNumbersVisibility(bool bIsVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetDamageNumbersVisibility");

	Params::KPhotoModePawn_SetDamageNumbersVisibility Parms{};

	Parms.bIsVisible = bIsVisible;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetEnemyVisibility
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bIsVisible                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetEnemyVisibility(bool bIsVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetEnemyVisibility");

	Params::KPhotoModePawn_SetEnemyVisibility Parms{};

	Parms.bIsVisible = bIsVisible;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetExposure
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InExposure                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetExposure(float InExposure)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetExposure");

	Params::KPhotoModePawn_SetExposure Parms{};

	Parms.InExposure = InExposure;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetFilmGrain
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InGrain                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetFilmGrain(float InGrain)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetFilmGrain");

	Params::KPhotoModePawn_SetFilmGrain Parms{};

	Parms.InGrain = InGrain;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetFilter
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    InFilterName                                           (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetFilter(const class FString& InFilterName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetFilter");

	Params::KPhotoModePawn_SetFilter Parms{};

	Parms.InFilterName = std::move(InFilterName);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetFilterByIndex
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   InFilterIndex                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetFilterByIndex(int32 InFilterIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetFilterByIndex");

	Params::KPhotoModePawn_SetFilterByIndex Parms{};

	Parms.InFilterIndex = InFilterIndex;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetFilterIntensity
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InIntensity                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetFilterIntensity(float InIntensity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetFilterIntensity");

	Params::KPhotoModePawn_SetFilterIntensity Parms{};

	Parms.InIntensity = InIntensity;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetFocusDistance
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InFocusDistance                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetFocusDistance(float InFocusDistance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetFocusDistance");

	Params::KPhotoModePawn_SetFocusDistance Parms{};

	Parms.InFocusDistance = InFocusDistance;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetFocusRegion
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InFocusRegion                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetFocusRegion(float InFocusRegion)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetFocusRegion");

	Params::KPhotoModePawn_SetFocusRegion Parms{};

	Parms.InFocusRegion = InFocusRegion;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetLensFlare
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InLensFlareIntensity                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetLensFlare(float InLensFlareIntensity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetLensFlare");

	Params::KPhotoModePawn_SetLensFlare Parms{};

	Parms.InLensFlareIntensity = InLensFlareIntensity;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetNPCVisibility
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bIsVisible                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetNPCVisibility(bool bIsVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetNPCVisibility");

	Params::KPhotoModePawn_SetNPCVisibility Parms{};

	Parms.bIsVisible = bIsVisible;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetPhotoModeFOV
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InFOV                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetPhotoModeFOV(float InFOV)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetPhotoModeFOV");

	Params::KPhotoModePawn_SetPhotoModeFOV Parms{};

	Parms.InFOV = InFOV;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetPhotoModeRoll
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InRoll                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetPhotoModeRoll(float InRoll)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetPhotoModeRoll");

	Params::KPhotoModePawn_SetPhotoModeRoll Parms{};

	Parms.InRoll = InRoll;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetPlayerAnimIdent
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    inAnimIdent                                            (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetPlayerAnimIdent(const class FString& inAnimIdent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetPlayerAnimIdent");

	Params::KPhotoModePawn_SetPlayerAnimIdent Parms{};

	Parms.inAnimIdent = std::move(inAnimIdent);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetPlayerCharacterVisibility
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bIsVisible                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetPlayerCharacterVisibility(bool bIsVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetPlayerCharacterVisibility");

	Params::KPhotoModePawn_SetPlayerCharacterVisibility Parms{};

	Parms.bIsVisible = bIsVisible;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetScreenContrast
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InContrast                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetScreenContrast(float InContrast)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetScreenContrast");

	Params::KPhotoModePawn_SetScreenContrast Parms{};

	Parms.InContrast = InContrast;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetScreenGain
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InGain                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetScreenGain(float InGain)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetScreenGain");

	Params::KPhotoModePawn_SetScreenGain Parms{};

	Parms.InGain = InGain;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetScreenGamma
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InGamma                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetScreenGamma(float InGamma)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetScreenGamma");

	Params::KPhotoModePawn_SetScreenGamma Parms{};

	Parms.InGamma = InGamma;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetScreenSaturation
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InSaturation                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetScreenSaturation(float InSaturation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetScreenSaturation");

	Params::KPhotoModePawn_SetScreenSaturation Parms{};

	Parms.InSaturation = InSaturation;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetSpawnParams
// (Final, Native, Private)

void AKPhotoModePawn::SetSpawnParams()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetSpawnParams");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetSummonVisibility
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bIsVisible                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetSummonVisibility(bool bIsVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetSummonVisibility");

	Params::KPhotoModePawn_SetSummonVisibility Parms{};

	Parms.bIsVisible = bIsVisible;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetTimeOfDay
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InTOD                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetTimeOfDay(float InTOD)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetTimeOfDay");

	Params::KPhotoModePawn_SetTimeOfDay Parms{};

	Parms.InTOD = InTOD;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.SetVignetteIntensity
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   InIntensity                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKPhotoModePawn::SetVignetteIntensity(float InIntensity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetVignetteIntensity");

	Params::KPhotoModePawn_SetVignetteIntensity Parms{};

	Parms.InIntensity = InIntensity;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.TryGetLocalController
// (Final, Native, Private)
// Parameters:
// class AController*                      ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class AController* AKPhotoModePawn::TryGetLocalController()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "TryGetLocalController");

	Params::KPhotoModePawn_TryGetLocalController Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModePawn.UpdateDamageNumbersVisibility
// (Final, Native, Private)

void AKPhotoModePawn::UpdateDamageNumbersVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "UpdateDamageNumbersVisibility");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModePawn.GetHeadBoneLocation
// (Final, Native, Private, HasDefaults, Const)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector AKPhotoModePawn::GetHeadBoneLocation() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "GetHeadBoneLocation");

	Params::KPhotoModePawn_GetHeadBoneLocation Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModePawn.SetCameraViewportSize
// (Final, Native, Private, Const)

void AKPhotoModePawn::SetCameraViewportSize() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModePawn", "SetCameraViewportSize");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModeSubsystem.AreFiltersValid
// (Final, Native, Public)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKPhotoModeSubsystem::AreFiltersValid()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "AreFiltersValid");

	Params::KPhotoModeSubsystem_AreFiltersValid Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModeSubsystem.GetActiveViewTarget
// (Final, Native, Private)
// Parameters:
// class AActor*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class AActor* UKPhotoModeSubsystem::GetActiveViewTarget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "GetActiveViewTarget");

	Params::KPhotoModeSubsystem_GetActiveViewTarget Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModeSubsystem.GetAnimationAssetByName
// (Final, Native, Public)
// Parameters:
// const class FString&                    assetname                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UAnimationAsset*                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UAnimationAsset* UKPhotoModeSubsystem::GetAnimationAssetByName(const class FString& assetname)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "GetAnimationAssetByName");

	Params::KPhotoModeSubsystem_GetAnimationAssetByName Parms{};

	Parms.assetname = std::move(assetname);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModeSubsystem.GetFilterLUTByIndex
// (Final, Native, Public)
// Parameters:
// const int32                             FilterIndex                                            (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UTexture*                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UTexture* UKPhotoModeSubsystem::GetFilterLUTByIndex(const int32 FilterIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "GetFilterLUTByIndex");

	Params::KPhotoModeSubsystem_GetFilterLUTByIndex Parms{};

	Parms.FilterIndex = FilterIndex;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModeSubsystem.GetFloatCurve
// (Final, Native, Public)
// Parameters:
// class UCurveFloat*                      ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UCurveFloat* UKPhotoModeSubsystem::GetFloatCurve()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "GetFloatCurve");

	Params::KPhotoModeSubsystem_GetFloatCurve Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModeSubsystem.GetInputMappingContext
// (Final, Native, Public)
// Parameters:
// class UInputMappingContext*             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UInputMappingContext* UKPhotoModeSubsystem::GetInputMappingContext()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "GetInputMappingContext");

	Params::KPhotoModeSubsystem_GetInputMappingContext Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModeSubsystem.GetLUTAssetNames
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TArray<class FString>                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class FString> UKPhotoModeSubsystem::GetLUTAssetNames()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "GetLUTAssetNames");

	Params::KPhotoModeSubsystem_GetLUTAssetNames Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModeSubsystem.GetLUTByAssetName
// (Final, Native, Public)
// Parameters:
// const class FString&                    FilterName                                             (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UTexture*                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UTexture* UKPhotoModeSubsystem::GetLUTByAssetName(const class FString& FilterName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "GetLUTByAssetName");

	Params::KPhotoModeSubsystem_GetLUTByAssetName Parms{};

	Parms.FilterName = std::move(FilterName);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModeSubsystem.GetLUTByFilterName
// (Final, Native, Public)
// Parameters:
// const class FString&                    FilterName                                             (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UTexture*                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UTexture* UKPhotoModeSubsystem::GetLUTByFilterName(const class FString& FilterName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "GetLUTByFilterName");

	Params::KPhotoModeSubsystem_GetLUTByFilterName Parms{};

	Parms.FilterName = std::move(FilterName);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PhotoMode.KPhotoModeSubsystem.GetTransformOffset
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// class AGbxPlayerController*             InOriginPlayerController                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector*                         OutLocation                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FRotator*                        OutRotation                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

void UKPhotoModeSubsystem::GetTransformOffset(class AGbxPlayerController* InOriginPlayerController, struct FVector* OutLocation, struct FRotator* OutRotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "GetTransformOffset");

	Params::KPhotoModeSubsystem_GetTransformOffset Parms{};

	Parms.InOriginPlayerController = InOriginPlayerController;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutLocation != nullptr)
		*OutLocation = std::move(Parms.OutLocation);

	if (OutRotation != nullptr)
		*OutRotation = std::move(Parms.OutRotation);
}


// Function PhotoMode.KPhotoModeSubsystem.GetTransformOffsetFromOrigin
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct FVector*                         OutLocation                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FRotator*                        OutRotation                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

void UKPhotoModeSubsystem::GetTransformOffsetFromOrigin(struct FVector* OutLocation, struct FRotator* OutRotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "GetTransformOffsetFromOrigin");

	Params::KPhotoModeSubsystem_GetTransformOffsetFromOrigin Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutLocation != nullptr)
		*OutLocation = std::move(Parms.OutLocation);

	if (OutRotation != nullptr)
		*OutRotation = std::move(Parms.OutRotation);
}


// Function PhotoMode.KPhotoModeSubsystem.LockOriginalPlayerCharacter
// (Final, Native, Private)
// Parameters:
// class AGbxCharacter*                    PlayerCharacter                                        (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKPhotoModeSubsystem::LockOriginalPlayerCharacter(class AGbxCharacter* PlayerCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "LockOriginalPlayerCharacter");

	Params::KPhotoModeSubsystem_LockOriginalPlayerCharacter Parms{};

	Parms.PlayerCharacter = PlayerCharacter;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModeSubsystem.RemoveFilterLUT
// (Final, Native, Public)

void UKPhotoModeSubsystem::RemoveFilterLUT()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "RemoveFilterLUT");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModeSubsystem.RemoveFloatCurve
// (Final, Native, Public)

void UKPhotoModeSubsystem::RemoveFloatCurve()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "RemoveFloatCurve");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModeSubsystem.RemoveInputMappingContext
// (Final, Native, Public)

void UKPhotoModeSubsystem::RemoveInputMappingContext()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "RemoveInputMappingContext");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModeSubsystem.RemovePoseAnimations
// (Final, Native, Public)

void UKPhotoModeSubsystem::RemovePoseAnimations()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "RemovePoseAnimations");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModeSubsystem.RevertToPreviousViewTarget
// (Final, Native, Public)

void UKPhotoModeSubsystem::RevertToPreviousViewTarget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "RevertToPreviousViewTarget");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModeSubsystem.UnlockOriginalPlayerCharacter
// (Final, Native, Private)
// Parameters:
// class AGbxCharacter*                    PlayerCharacter                                        (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKPhotoModeSubsystem::UnlockOriginalPlayerCharacter(class AGbxCharacter* PlayerCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "UnlockOriginalPlayerCharacter");

	Params::KPhotoModeSubsystem_UnlockOriginalPlayerCharacter Parms{};

	Parms.PlayerCharacter = PlayerCharacter;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PhotoMode.KPhotoModeSubsystem.GetOrSetPhotoModeSettings
// (Final, RequiredAPI, Native, Public, Const)
// Parameters:
// const class UKPhotoModeSettings*        ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const class UKPhotoModeSettings* UKPhotoModeSubsystem::GetOrSetPhotoModeSettings() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KPhotoModeSubsystem", "GetOrSetPhotoModeSettings");

	Params::KPhotoModeSubsystem_GetOrSetPhotoModeSettings Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

