#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_CarryableContainer_MeteorDestroyer_Railgun

#include "Basic.hpp"

#include "Script_CarryableContainer_MeteorDestroyer_Railgun_classes.hpp"
#include "Script_CarryableContainer_MeteorDestroyer_Railgun_parameters.hpp"


namespace SDK
{

// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.AboutToFire__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::AboutToFire__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "AboutToFire__OnStateEnabled");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_AboutToFire__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.AddHit__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::AddHit__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "AddHit__OnStateEnabled");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_AddHit__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.destroyed__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::destroyed__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "destroyed__OnStateEnabled");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_destroyed__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.ExecuteUbergraph_Script_CarryableContainer_MeteorDestroyer_Railgun
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::ExecuteUbergraph_Script_CarryableContainer_MeteorDestroyer_Railgun(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "ExecuteUbergraph_Script_CarryableContainer_MeteorDestroyer_Railgun");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_ExecuteUbergraph_Script_CarryableContainer_MeteorDestroyer_Railgun Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.FinishLoading__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::FinishLoading__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "FinishLoading__OnStateEnabled");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_FinishLoading__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.FireFinished__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::FireFinished__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "FireFinished__OnStateEnabled");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_FireFinished__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.FireGun__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::FireGun__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "FireGun__OnStateEnabled");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_FireGun__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.Firing__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::Firing__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "Firing__OnStateEnabled");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_Firing__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.GbxActorScriptEvt__Blackboard_ValueChangedEventBP
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxBlackboardEntryRef&    Entry                                                  (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::GbxActorScriptEvt__Blackboard_ValueChangedEventBP(const struct FGbxBlackboardEntryRef& Entry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "GbxActorScriptEvt__Blackboard_ValueChangedEventBP");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_GbxActorScriptEvt__Blackboard_ValueChangedEventBP Parms{};

	Parms.Entry = std::move(Entry);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.Loaded__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::Loaded__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "Loaded__OnStateEnabled");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_Loaded__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.LoadIdle__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::LoadIdle__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "LoadIdle__OnStateEnabled");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_LoadIdle__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.MeteorExplode
// (Public, BlueprintCallable, BlueprintEvent)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::MeteorExplode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "MeteorExplode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.OpenToLoad__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::OpenToLoad__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "OpenToLoad__OnStateEnabled");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_OpenToLoad__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.RemindManagerFinished
// (Public, BlueprintCallable, BlueprintEvent)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::RemindManagerFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "RemindManagerFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.RemindMeteorFinished
// (Public, BlueprintCallable, BlueprintEvent)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::RemindMeteorFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "RemindMeteorFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.SetManager
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Manager_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::SetManager(class AActor* Manager_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "SetManager");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_SetManager Parms{};

	Parms.Manager_0 = Manager_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.SpawnLoot__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::SpawnLoot__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "SpawnLoot__OnStateEnabled");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_SpawnLoot__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.StartExplode
// (Public, BlueprintCallable, BlueprintEvent)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::StartExplode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "StartExplode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.TransferAcceleration
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Acceleration                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::TransferAcceleration(double Acceleration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "TransferAcceleration");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_TransferAcceleration Parms{};

	Parms.Acceleration = Acceleration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.TransferExplosionCount
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ExplosionCount                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::TransferExplosionCount(int32 ExplosionCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "TransferExplosionCount");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_TransferExplosionCount Parms{};

	Parms.ExplosionCount = ExplosionCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.TransferLoadedOreCount
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   LoadedOreCount                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::TransferLoadedOreCount(int32 LoadedOreCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "TransferLoadedOreCount");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_TransferLoadedOreCount Parms{};

	Parms.LoadedOreCount = LoadedOreCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_CarryableContainer_MeteorDestroyer_Railgun.Script_CarryableContainer_MeteorDestroyer_Railgun_C.Unloaded__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_CarryableContainer_MeteorDestroyer_Railgun_C::Unloaded__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_CarryableContainer_MeteorDestroyer_Railgun_C", "Unloaded__OnStateEnabled");

	Params::Script_CarryableContainer_MeteorDestroyer_Railgun_C_Unloaded__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}

}

