#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Script_Carryable_ExplodingObject_PropaneTank

#include "Basic.hpp"

#include "Script_Carryable_ExplodingObject_PropaneTank_classes.hpp"
#include "Script_Carryable_ExplodingObject_PropaneTank_parameters.hpp"


namespace SDK
{

// Function Script_Carryable_ExplodingObject_PropaneTank.Script_Carryable_ExplodingObject_PropaneTank_C.ExecuteUbergraph_Script_Carryable_ExplodingObject_PropaneTank
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   entrypoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_Carryable_ExplodingObject_PropaneTank_C::ExecuteUbergraph_Script_Carryable_ExplodingObject_PropaneTank(int32 entrypoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_Carryable_ExplodingObject_PropaneTank_C", "ExecuteUbergraph_Script_Carryable_ExplodingObject_PropaneTank");

	Params::Script_Carryable_ExplodingObject_PropaneTank_C_ExecuteUbergraph_Script_Carryable_ExplodingObject_PropaneTank Parms{};

	Parms.entrypoint = entrypoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Script_Carryable_ExplodingObject_PropaneTank.Script_Carryable_ExplodingObject_PropaneTank_C.Exploding__OnStateEnabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGbxActorStateMachineStateKey&PreviousState                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScript_Carryable_ExplodingObject_PropaneTank_C::Exploding__OnStateEnabled(const struct FGbxActorStateMachineStateKey& PreviousState, bool bIsInitialState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Script_Carryable_ExplodingObject_PropaneTank_C", "Exploding__OnStateEnabled");

	Params::Script_Carryable_ExplodingObject_PropaneTank_C_Exploding__OnStateEnabled Parms{};

	Parms.PreviousState = std::move(PreviousState);
	Parms.bIsInitialState = bIsInitialState;

	UObject::ProcessEvent(Func, &Parms);
}

}

