#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TScript_TED_Reload

#include "Basic.hpp"

#include "GbxGame_structs.hpp"
#include "GbxGame_classes.hpp"
#include "GbxEngine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass TScript_TED_Reload.TScript_TED_Reload_C
// 0x0010 (0x0050 - 0x0040)
class UTScript_TED_Reload_C final : public UGbxTrickScript
{
public:
	class UGbxTrick_CoordinatedEffect*            DigistructCFX;                                     // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class AWeapon*                                MyWeapon;                                          // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void CalculateExplosionDamage(class AWeapon* Weapon, double* ExplosionDamage) const;
	void OnAnimNotify(class AActor* Actor, const struct FGameplayTag& Tag, bool bTrickHasEnded) const;
	void OnAnimNotifyState(class AActor* Actor, const struct FGameplayTag& Tag, EGbxTrickAnimNotifyState type, bool bTrickHasEnded) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TScript_TED_Reload_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TScript_TED_Reload_C")
	}
	static class UTScript_TED_Reload_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTScript_TED_Reload_C>();
	}
};
DUMPER7_ASSERTS_UTScript_TED_Reload_C;

}

